# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'IPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IPI
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'
  
  target 'IPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
